micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root123'
jpa.default.properties.hibernate.hbm2ddl.auto: update